apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: projeto-tcc
spec:
  destinations:
  - namespace: argocd
    server: https://kubernetes.default.svc
  sourceRepos:
  - 'https://github.com/MarcioSbicigo/mybudget-deploy.git'