apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tcc-apps
spec:
  generators:
    - git:
        repoURL: https://github.com/MarcioSbicigo/mybudget-deploy.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      destination:
        name: ''
        namespace: argocd
        server: https://kubernetes.default.svc
      source:
        path: '{{path}}'
        repoURL: https://github.com/MarcioSbicigo/mybudget-deploy.git
        targetRevision: HEAD
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true